# Production environment patches for Learner Graph RAG System

# Increase resources for production workload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-graph-app
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: learner-graph-api
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
        - name: LOG_LEVEL
          value: "WARNING"
        - name: RECOMMENDATION_CACHE_TTL
          value: "600"  # 10 minutes in production
        - name: MAX_RECOMMENDATIONS
          value: "20"   # More recommendations in production

---
# Production Redis configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
# Production service configuration
apiVersion: v1
kind: Service
metadata:
  name: learner-graph-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:123456789012:certificate/12345678-1234-1234-1234-123456789012"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer

---
# Production HPA with more aggressive scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: learner-graph-hpa
spec:
  minReplicas: 5
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Lower threshold for production
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # Lower threshold for production 